name: "Lyrics"
guid: "F4A1B2C3-D4E5-6F7A-8B9C-0D1E2F3A4B5C"
version: "1.3"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "Felitendo"
overview: "Lyrics plugin with configurable search options and automatic library scanning"
description: >
  Lyrics plugin that downloads lyrics from lrclib.net with configurable search options

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Lyrics.dll"
changelog: |-
  ## v1.3.0.0
  ### What's New
  - Fixed a lot of plugin loading issues
  - Fixed GitHub Action Workflows
  
  ### Technical Improvements
  - Consistent versioning across all project files
  - Better package compatibility with Jellyfin 10.9.x series
  - Improved documentation and installation instructions
